### ISSUE TITLE
The Codacy badge on the project README does not lead to the Codacy dashboard

### ISSUE THREAD

**Issue by zwliew** [jboss-outreach/wiki-explorer#20]
Currently, the Codacy badge (introduced in PR #19) is missing the link to the Codacy dashboard of the project. The link to the Codacy dashboard should be added to the end of the line.

For reference, a similar [change on the jboss-outreach/gci ](https://github.com/jboss-outreach/gci/pull/11) adds the link to the Codacy dashboard to the end of the line.

**Comment by garg-anuj** [comment]
@zwliew would you like to resolve it?

**Comment by zwliew** [comment]
@garg-anuj I've set up a PR at #24. I don't think Codacy is set up for this repository yet however, so that needs to be taken care of.

**Comment by zwliew** [comment]
Addressed.
